name: Erlang CI

on:
  push:
  pull_request:

jobs:

  test:
    strategy:
      matrix:
        otp_release:
          - "24.2"
          - "23.3"

    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:5
        ports:
        - 27017:27017
        
    container:
      image: erlang:${otp_release}

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: make tests
    - name: edoc
      run: make docs
